### PR TITLE
Fix DeadlockSafe component errors, update SDK and dependencies

### LINKED ISSUE #77: Wrong component's Instantiations flags
Some ReSharper component's attributes marked as `DeadlockSafe` by default, but not all of them, and we should not inject usual `ShellComponent` into `DeadlockSafe` components.

For example,  we need to check that `GenericSettingsSuggestionProvider`  doesn't depends on MainThread (it's true), and mark it as `[ShellComponent(Instantiation.DemandAnyThreadSafe)]`

```
15:53:32.702 |E| AsyncDescriptorBase           | JetPool(S) #6:35   | Component Resharper.ConfigurationSense.SuggestionProviders.AppSettingsSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe

--- EXCEPTION #1/2 [Exception]
Message = “Component Resharper.ConfigurationSense.SuggestionProviders.AppSettingsSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe”
Data.Descriptor = Resharper.ConfigurationSense.SuggestionProviders.AppSettingsSuggestionProvider
Data.DescriptorType = “JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor, JetBrains.Platform.ComponentModel, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
Data.State = Null
Data.IsSyncMode = False
Data.Instantiation = DemandAnyThreadSafe
Data.IsCreationAllowed = True
Data.IsPrimaryThread = False
Data.Container = PsiLanguageType:CSHARP
Data.ContainerState = Composed
Data.PartCatalogType = “Resharper.ConfigurationSense.SuggestionProviders.AppSettingsSuggestionProvider, Resharper.ConfigurationSense, Version=2025.1.4.207, Culture=neutral, PublicKeyToken=null”
Data.ViolatingDependency = Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider
Data.Dependency_Descriptor = Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider
Data.Dependency_DescriptorType = “JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor, JetBrains.Platform.ComponentModel, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
Data.Dependency_State = Null
Data.Dependency_IsSyncMode = False
Data.Dependency_Instantiation = UnspecifiedDefault
Data.Dependency_IsCreationAllowed = False
Data.Dependency_IsPrimaryThread = False
Data.Dependency_Container = Shell
Data.Dependency_ContainerState = Created
Data.Dependency_PartCatalogType = “Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider, Resharper.ConfigurationSense, Version=2025.1.4.207, Culture=neutral, PublicKeyToken=null”
ExceptionPath = Root.InnerException
ClassName = System.Exception
HResult = COR_E_EXCEPTION=80131500

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Component Resharper.ConfigurationSense.SuggestionProviders.AppSettingsSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe”
Data.ManagedThreadName = “JetPool(S) #6”
InnerException = “Exception #1 at Root.InnerException”
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogException(ILogger logger, LoggingLevel level, Exception exception, ExceptionOrigin exceptionOrigin, String comment) in LogException.il:line IL_0025 mvid 8B40 or LogException.il:line IL_002E mvid 8B40
     at JetBrains.Util.ILoggerEx.LogException(ILogger logger, Exception exception) in LogException.il:line IL_0025 mvid 8B40 or LogException.il:line IL_002E mvid 8B40
     at JetBrains.Application.Components.AsyncDescriptorBase.DoGetDependenciesAsync(Boolean forceSync) in DoGetDependenciesAsync.il:line IL_02F1 mvid 44CD
     at JetBrains.Application.Components.AsyncDescriptorBase.GetDependencies() in GetDependencies.il:line IL_000E mvid 44CD
     at JetBrains.Application.Components.ComponentStorage.<WarmUpDescriptors>g__ProcessListCore|26_4(IEnumerable`1 initialDescriptors, <>c__DisplayClass26_0& ) in ComponentStorage.il:line IL_0044 mvid 44CD
     at JetBrains.Application.Components.ComponentStorage.WarmUpDescriptors(Lifetime lifetime, ICollection`1 descriptors, String containerId) in WarmUpDescriptors.il:line IL_00FF mvid 44CD
     at System.Threading.Tasks.Task.Execute() in Execute.il:line IL_0010 mvid 3020
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in RunInternal.il:line IL_0079 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in ExecuteWithThreadLocal.il:line IL_00E1 mvid 3020
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution) in ExecuteEntry.il:line IL_0096 mvid 3020
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task) in ExecuteTask.il:line IL_001C mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask() in EnqueueNextTask.il:line IL_0015 mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc() in ThreadPoolProc.il:line IL_0197 mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.StartProc() in StartProc.il:line IL_0000 mvid 8B40
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in RunInternal.il:line IL_0079 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.ThreadHelper.ThreadStart() in ThreadStart.il:line IL_002A mvid 3020
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600

23:43:59.197 |E| AsyncDescriptorBase           | JetPool(S) #6:35   | Component Resharper.ConfigurationSense.SuggestionProviders.ConnectionStringsSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe

--- EXCEPTION #1/2 [Exception]
Message = “Component Resharper.ConfigurationSense.SuggestionProviders.ConnectionStringsSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe”
Data.Descriptor = Resharper.ConfigurationSense.SuggestionProviders.ConnectionStringsSuggestionProvider
Data.DescriptorType = “JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor, JetBrains.Platform.ComponentModel, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
Data.State = Null
Data.IsSyncMode = False
Data.Instantiation = DemandAnyThreadSafe
Data.IsCreationAllowed = True
Data.IsPrimaryThread = False
Data.Container = PsiLanguageType:CSHARP
Data.ContainerState = Composed
Data.PartCatalogType = “Resharper.ConfigurationSense.SuggestionProviders.ConnectionStringsSuggestionProvider, Resharper.ConfigurationSense, Version=2025.1.4.207, Culture=neutral, PublicKeyToken=null”
Data.ViolatingDependency = Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider
Data.Dependency_Descriptor = Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider
Data.Dependency_DescriptorType = “JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor, JetBrains.Platform.ComponentModel, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
Data.Dependency_State = Initialized
Data.Dependency_IsSyncMode = False
Data.Dependency_Instantiation = UnspecifiedDefault
Data.Dependency_IsCreationAllowed = False
Data.Dependency_IsPrimaryThread = False
Data.Dependency_Container = Shell
Data.Dependency_ContainerState = Composed
Data.Dependency_PartCatalogType = “Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider, Resharper.ConfigurationSense, Version=2025.1.4.207, Culture=neutral, PublicKeyToken=null”
ExceptionPath = Root.InnerException
ClassName = System.Exception
HResult = COR_E_EXCEPTION=80131500

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Component Resharper.ConfigurationSense.SuggestionProviders.ConnectionStringsSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe”
Data.ManagedThreadName = “JetPool(S) #6”
InnerException = “Exception #1 at Root.InnerException”
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogException(ILogger logger, LoggingLevel level, Exception exception, ExceptionOrigin exceptionOrigin, String comment) in LogException.il:line IL_0025 mvid 8B40 or LogException.il:line IL_002E mvid 8B40
     at JetBrains.Util.ILoggerEx.LogException(ILogger logger, Exception exception) in LogException.il:line IL_0025 mvid 8B40 or LogException.il:line IL_002E mvid 8B40
     at JetBrains.Application.Components.AsyncDescriptorBase.DoGetDependenciesAsync(Boolean forceSync) in DoGetDependenciesAsync.il:line IL_02F1 mvid 44CD
     at JetBrains.Application.Components.AsyncDescriptorBase.GetDependencies() in GetDependencies.il:line IL_000E mvid 44CD
     at JetBrains.Application.Components.ComponentStorage.<WarmUpDescriptors>g__ProcessListCore|26_4(IEnumerable`1 initialDescriptors, <>c__DisplayClass26_0& ) in ComponentStorage.il:line IL_0044 mvid 44CD
     at JetBrains.Application.Components.ComponentStorage.WarmUpDescriptors(Lifetime lifetime, ICollection`1 descriptors, String containerId) in WarmUpDescriptors.il:line IL_00FF mvid 44CD
     at System.Threading.Tasks.Task.Execute() in Execute.il:line IL_0010 mvid 3020
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in RunInternal.il:line IL_0079 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in ExecuteWithThreadLocal.il:line IL_00E1 mvid 3020
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution) in ExecuteEntry.il:line IL_0096 mvid 3020
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task) in ExecuteTask.il:line IL_001C mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask() in EnqueueNextTask.il:line IL_0015 mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc() in ThreadPoolProc.il:line IL_0197 mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.StartProc() in StartProc.il:line IL_0000 mvid 8B40
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in RunInternal.il:line IL_0079 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.ThreadHelper.ThreadStart() in ThreadStart.il:line IL_002A mvid 3020
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600

23:43:59.204 |E| AsyncDescriptorBase           | JetPool(S) #6:35   | Component Resharper.ConfigurationSense.SuggestionProviders.NetCoreConfigurationSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe

--- EXCEPTION #1/2 [Exception]
Message = “Component Resharper.ConfigurationSense.SuggestionProviders.NetCoreConfigurationSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe”
Data.Descriptor = Resharper.ConfigurationSense.SuggestionProviders.NetCoreConfigurationSuggestionProvider
Data.DescriptorType = “JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor, JetBrains.Platform.ComponentModel, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
Data.State = Null
Data.IsSyncMode = False
Data.Instantiation = DemandAnyThreadSafe
Data.IsCreationAllowed = True
Data.IsPrimaryThread = False
Data.Container = PsiLanguageType:CSHARP
Data.ContainerState = Composed
Data.PartCatalogType = “Resharper.ConfigurationSense.SuggestionProviders.NetCoreConfigurationSuggestionProvider, Resharper.ConfigurationSense, Version=2025.1.4.207, Culture=neutral, PublicKeyToken=null”
Data.ViolatingDependency = Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider
Data.Dependency_Descriptor = Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider
Data.Dependency_DescriptorType = “JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor, JetBrains.Platform.ComponentModel, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
Data.Dependency_State = Initialized
Data.Dependency_IsSyncMode = False
Data.Dependency_Instantiation = UnspecifiedDefault
Data.Dependency_IsCreationAllowed = False
Data.Dependency_IsPrimaryThread = False
Data.Dependency_Container = Shell
Data.Dependency_ContainerState = Composed
Data.Dependency_PartCatalogType = “Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider, Resharper.ConfigurationSense, Version=2025.1.4.207, Culture=neutral, PublicKeyToken=null”
ExceptionPath = Root.InnerException
ClassName = System.Exception
HResult = COR_E_EXCEPTION=80131500

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Component Resharper.ConfigurationSense.SuggestionProviders.NetCoreConfigurationSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe”
Data.ManagedThreadName = “JetPool(S) #6”
InnerException = “Exception #1 at Root.InnerException”
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogException(ILogger logger, LoggingLevel level, Exception exception, ExceptionOrigin exceptionOrigin, String comment) in LogException.il:line IL_0025 mvid 8B40 or LogException.il:line IL_002E mvid 8B40
     at JetBrains.Util.ILoggerEx.LogException(ILogger logger, Exception exception) in LogException.il:line IL_0025 mvid 8B40 or LogException.il:line IL_002E mvid 8B40
     at JetBrains.Application.Components.AsyncDescriptorBase.DoGetDependenciesAsync(Boolean forceSync) in DoGetDependenciesAsync.il:line IL_02F1 mvid 44CD
     at JetBrains.Application.Components.AsyncDescriptorBase.GetDependencies() in GetDependencies.il:line IL_000E mvid 44CD
     at JetBrains.Application.Components.ComponentStorage.<WarmUpDescriptors>g__ProcessListCore|26_4(IEnumerable`1 initialDescriptors, <>c__DisplayClass26_0& ) in ComponentStorage.il:line IL_0044 mvid 44CD
     at JetBrains.Application.Components.ComponentStorage.WarmUpDescriptors(Lifetime lifetime, ICollection`1 descriptors, String containerId) in WarmUpDescriptors.il:line IL_00FF mvid 44CD
     at System.Threading.Tasks.Task.Execute() in Execute.il:line IL_0010 mvid 3020
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in RunInternal.il:line IL_0079 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in ExecuteWithThreadLocal.il:line IL_00E1 mvid 3020
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution) in ExecuteEntry.il:line IL_0096 mvid 3020
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task) in ExecuteTask.il:line IL_001C mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask() in EnqueueNextTask.il:line IL_0015 mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc() in ThreadPoolProc.il:line IL_0197 mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.StartProc() in StartProc.il:line IL_0000 mvid 8B40
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in RunInternal.il:line IL_0079 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.ThreadHelper.ThreadStart() in ThreadStart.il:line IL_002A mvid 3020
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600

23:43:59.214 |E| AsyncDescriptorBase           | JetPool(S) #6:35   | Component Resharper.ConfigurationSense.SuggestionProviders.NetCoreConnectionStringsSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe

--- EXCEPTION #1/2 [Exception]
Message = “Component Resharper.ConfigurationSense.SuggestionProviders.NetCoreConnectionStringsSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe”
Data.Descriptor = Resharper.ConfigurationSense.SuggestionProviders.NetCoreConnectionStringsSuggestionProvider
Data.DescriptorType = “JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor, JetBrains.Platform.ComponentModel, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
Data.State = Null
Data.IsSyncMode = False
Data.Instantiation = DemandAnyThreadSafe
Data.IsCreationAllowed = True
Data.IsPrimaryThread = False
Data.Container = PsiLanguageType:CSHARP
Data.ContainerState = Composed
Data.PartCatalogType = “Resharper.ConfigurationSense.SuggestionProviders.NetCoreConnectionStringsSuggestionProvider, Resharper.ConfigurationSense, Version=2025.1.4.207, Culture=neutral, PublicKeyToken=null”
Data.ViolatingDependency = Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider
Data.Dependency_Descriptor = Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider
Data.Dependency_DescriptorType = “JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor, JetBrains.Platform.ComponentModel, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
Data.Dependency_State = Initialized
Data.Dependency_IsSyncMode = False
Data.Dependency_Instantiation = UnspecifiedDefault
Data.Dependency_IsCreationAllowed = False
Data.Dependency_IsPrimaryThread = False
Data.Dependency_Container = Shell
Data.Dependency_ContainerState = Composed
Data.Dependency_PartCatalogType = “Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider, Resharper.ConfigurationSense, Version=2025.1.4.207, Culture=neutral, PublicKeyToken=null”
ExceptionPath = Root.InnerException
ClassName = System.Exception
HResult = COR_E_EXCEPTION=80131500

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Component Resharper.ConfigurationSense.SuggestionProviders.NetCoreConnectionStringsSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe”
Data.ManagedThreadName = “JetPool(S) #6”
InnerException = “Exception #1 at Root.InnerException”
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogException(ILogger logger, LoggingLevel level, Exception exception, ExceptionOrigin exceptionOrigin, String comment) in LogException.il:line IL_0025 mvid 8B40 or LogException.il:line IL_002E mvid 8B40
     at JetBrains.Util.ILoggerEx.LogException(ILogger logger, Exception exception) in LogException.il:line IL_0025 mvid 8B40 or LogException.il:line IL_002E mvid 8B40
     at JetBrains.Application.Components.AsyncDescriptorBase.DoGetDependenciesAsync(Boolean forceSync) in DoGetDependenciesAsync.il:line IL_02F1 mvid 44CD
     at JetBrains.Application.Components.AsyncDescriptorBase.GetDependencies() in GetDependencies.il:line IL_000E mvid 44CD
     at JetBrains.Application.Components.ComponentStorage.<WarmUpDescriptors>g__ProcessListCore|26_4(IEnumerable`1 initialDescriptors, <>c__DisplayClass26_0& ) in ComponentStorage.il:line IL_0044 mvid 44CD
     at JetBrains.Application.Components.ComponentStorage.WarmUpDescriptors(Lifetime lifetime, ICollection`1 descriptors, String containerId) in WarmUpDescriptors.il:line IL_00FF mvid 44CD
     at System.Threading.Tasks.Task.Execute() in Execute.il:line IL_0010 mvid 3020
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in RunInternal.il:line IL_0079 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in ExecuteWithThreadLocal.il:line IL_00E1 mvid 3020
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution) in ExecuteEntry.il:line IL_0096 mvid 3020
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task) in ExecuteTask.il:line IL_001C mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask() in EnqueueNextTask.il:line IL_0015 mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc() in ThreadPoolProc.il:line IL_0197 mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.StartProc() in StartProc.il:line IL_0000 mvid 8B40
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in RunInternal.il:line IL_0079 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.ThreadHelper.ThreadStart() in ThreadStart.il:line IL_002A mvid 3020
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600

23:43:59.221 |E| AsyncDescriptorBase           | JetPool(S) #6:35   | Component Resharper.ConfigurationSense.SuggestionProviders.NetCoreGetSectionSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe

--- EXCEPTION #1/2 [Exception]
Message = “Component Resharper.ConfigurationSense.SuggestionProviders.NetCoreGetSectionSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe”
Data.Descriptor = Resharper.ConfigurationSense.SuggestionProviders.NetCoreGetSectionSuggestionProvider
Data.DescriptorType = “JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor, JetBrains.Platform.ComponentModel, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
Data.State = Null
Data.IsSyncMode = False
Data.Instantiation = DemandAnyThreadSafe
Data.IsCreationAllowed = True
Data.IsPrimaryThread = False
Data.Container = PsiLanguageType:CSHARP
Data.ContainerState = Composed
Data.PartCatalogType = “Resharper.ConfigurationSense.SuggestionProviders.NetCoreGetSectionSuggestionProvider, Resharper.ConfigurationSense, Version=2025.1.4.207, Culture=neutral, PublicKeyToken=null”
Data.ViolatingDependency = Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider
Data.Dependency_Descriptor = Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider
Data.Dependency_DescriptorType = “JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor, JetBrains.Platform.ComponentModel, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325”
Data.Dependency_State = Initialized
Data.Dependency_IsSyncMode = False
Data.Dependency_Instantiation = UnspecifiedDefault
Data.Dependency_IsCreationAllowed = False
Data.Dependency_IsPrimaryThread = False
Data.Dependency_Container = Shell
Data.Dependency_ContainerState = Composed
Data.Dependency_PartCatalogType = “Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider, Resharper.ConfigurationSense, Version=2025.1.4.207, Culture=neutral, PublicKeyToken=null”
ExceptionPath = Root.InnerException
ClassName = System.Exception
HResult = COR_E_EXCEPTION=80131500

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Component Resharper.ConfigurationSense.SuggestionProviders.NetCoreGetSectionSuggestionProvider is DeadlockSafe (DemandAnyThreadSafe), but it requires Resharper.ConfigurationSense.Components.GenericSettingsSuggestionProvider which is not DeadlockSafe”
InnerException = “Exception #1 at Root.InnerException”
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogException(ILogger logger, LoggingLevel level, Exception exception, ExceptionOrigin exceptionOrigin, String comment) in LogException.il:line IL_0025 mvid 8B40 or LogException.il:line IL_002E mvid 8B40
     at JetBrains.Util.ILoggerEx.LogException(ILogger logger, Exception exception) in LogException.il:line IL_0025 mvid 8B40 or LogException.il:line IL_002E mvid 8B40
     at JetBrains.Application.Components.AsyncDescriptorBase.DoGetDependenciesAsync(Boolean forceSync) in DoGetDependenciesAsync.il:line IL_02F1 mvid 44CD
     at JetBrains.Application.Components.AsyncDescriptorBase.GetDependencies() in GetDependencies.il:line IL_000E mvid 44CD
     at JetBrains.Application.Components.ComponentStorage.<WarmUpDescriptors>g__ProcessListCore|26_4(IEnumerable`1 initialDescriptors, <>c__DisplayClass26_0& ) in ComponentStorage.il:line IL_0044 mvid 44CD
     at JetBrains.Application.Components.ComponentStorage.WarmUpDescriptors(Lifetime lifetime, ICollection`1 descriptors, String containerId) in WarmUpDescriptors.il:line IL_00FF mvid 44CD
     at System.Threading.Tasks.Task.Execute() in Execute.il:line IL_0010 mvid 3020
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in RunInternal.il:line IL_0079 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot) in ExecuteWithThreadLocal.il:line IL_00E1 mvid 3020
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution) in ExecuteEntry.il:line IL_0096 mvid 3020
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task) in ExecuteTask.il:line IL_001C mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask() in EnqueueNextTask.il:line IL_0015 mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc() in ThreadPoolProc.il:line IL_0197 mvid 8B40
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.StartProc() in StartProc.il:line IL_0000 mvid 8B40
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in RunInternal.il:line IL_0079 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in Run.il:line IL_0009 mvid 3020 or Run.il:line IL_0034 mvid 3020
     at System.Threading.ThreadHelper.ThreadStart() in ThreadStart.il:line IL_002A mvid 3020
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600
```

### PR DESCRIPTION
**Pull request by olsh**
## Summary

- Fix DeadlockSafe validation errors by removing `IGenericSettingsProvider` interface and injecting concrete `GenericSettingsSuggestionProvider` directly into all suggestion providers (fixes #77)
- Mark `GenericSettingsSuggestionProvider` with `Instantiation.DemandAnyThreadSafe`
- Update JetBrains SDK to 2025.3.3
- Update Nuke.Common 8.1.4 → 9.0.4, dotnet-sonarscanner 5.13.1 → 11.1.0, NuGet.CommandLine 6.5.0 → 7.3.0
- Update AppVeyor JDK from 17 to 21, Gradle JVM target to 21
- Update IntelliJ Platform plugin to 2.11.0 and Kotlin to 2.3.10
- Update .gitignore for build artifacts and tooling

### CODE REVIEW

File: src/Resharper.ConfigurationSense/SuggestionProviders/AppSettingsSuggestionProvider.cs [hunk 1]
```diff
@@ -14,9 +14,9 @@ namespace Resharper.ConfigurationSense.SuggestionProviders
     [Language(typeof(CSharpLanguage))]
     public class AppSettingsSuggestionProvider : ItemsProviderOfSpecificContext<CSharpCodeCompletionContext>
     {
-        private readonly IGenericSettingsProvider _genericSettingsProvider;
+        private readonly GenericSettingsSuggestionProvider _genericSettingsProvider;
 
-        public AppSettingsSuggestionProvider(IGenericSettingsProvider genericSettingsProvider)
+        public AppSettingsSuggestionProvider(GenericSettingsSuggestionProvider genericSettingsProvider)
```
Comment (poksh) [inline src/Resharper.ConfigurationSense/SuggestionProviders/AppSettingsSuggestionProvider.cs]: BTW interfaces can be used in injections into DeadlockSafe components when they marked by `[DerivedComponentsInstantiationRequirement(InstantiationRequirement.DeadlockSafe)]`

**Review by poksh — APPROVED** [review]
Thanks!
